(defun reco(a)
  (princ a)
  (if (= (car a) 0)
      (princ "hola k ase ")
    (reco (cdr a) )
    )
  )

(defun reca(a)
  (if (eq (car a) nil )
      (princ "Elemento nulo ")
    (princ "Elemento no nulo")
      )
)
